"""AgentSpec-Commerce declarative policy loading.

This module uses the parser generated by the pinned official AgentSpec
repository, but does not use AgentSpec's LangChain executor, RuleState,
Action, interpreter, or enforcement implementations.

Official AgentSpec provenance:
    https://github.com/haoyuwang99/AgentSpec
    commit e6fa3902e2cfb9681f454b355691b771f70543f8
"""

from __future__ import annotations

import os
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

AGENTSPEC_REPO_URL = "https://github.com/haoyuwang99/AgentSpec"
AGENTSPEC_PINNED_COMMIT = "e6fa3902e2cfb9681f454b355691b771f70543f8"
AGENTSPEC_SRC_ENV = "AIMAI_AGENTSPEC_SRC"

DEFAULT_POLICY_PATH = (
    Path(__file__).resolve().parent / "policies" / "commerce_policy.ar"
)

_REQUIRED_PARSER_FILES = (
    "spec_lang/AgentSpecLexer.py",
    "spec_lang/AgentSpecListener.py",
    "spec_lang/AgentSpecParser.py",
)


class AgentSpecPolicyError(RuntimeError):
    """Base error for AgentSpec-Commerce policy loading."""


class AgentSpecUnavailableError(AgentSpecPolicyError):
    """Raised when the pinned AgentSpec parser cannot be found."""


class AgentSpecVersionError(AgentSpecPolicyError):
    """Raised when the external checkout is not at the pinned commit."""


class AgentSpecSyntaxError(AgentSpecPolicyError):
    """Raised when a policy cannot be parsed by the AgentSpec grammar."""


class AgentSpecPolicyShapeError(AgentSpecPolicyError):
    """Raised when a rule uses a policy shape unsupported by this adapter."""


@dataclass(frozen=True)
class ParsedRule:
    """One parsed AgentSpec-Commerce rule."""

    rule_id: str
    event: str
    predicate_name: str
    predicate_version: int
    enforcement: str
    raw: str


def resolve_agentspec_src(
    explicit: str | Path | None = None,
) -> Path:
    """Locate the external AgentSpec src directory.

    AgentSpec is kept outside this repository because its upstream repository
    does not currently include a licence file. No upstream source is vendored
    into aimai_ocl.
    """
    candidates: list[Path] = []

    if explicit is not None:
        candidates.append(Path(explicit))

    env_path = os.getenv(AGENTSPEC_SRC_ENV)
    if env_path:
        candidates.append(Path(env_path))

    candidates.extend(
        [
            Path("/workspaces/third_party/AgentSpec/src"),
            Path("artifacts/third_party/AgentSpec/src"),
        ]
    )

    checked: list[str] = []

    for candidate in candidates:
        source = candidate.expanduser().resolve()
        checked.append(str(source))

        if all((source / relative).is_file() for relative in _REQUIRED_PARSER_FILES):
            return source

    raise AgentSpecUnavailableError(
        "Could not locate the AgentSpec parser. Checked: "
        + ", ".join(checked)
        + ". Set "
        + AGENTSPEC_SRC_ENV
        + " to the pinned AgentSpec src directory."
    )


def verify_pinned_checkout(source: Path) -> str:
    """Verify that the external AgentSpec checkout matches the pinned commit."""
    repository = source.parent

    try:
        completed = subprocess.run(
            ["git", "-C", str(repository), "rev-parse", "HEAD"],
            check=True,
            capture_output=True,
            text=True,
        )
    except (OSError, subprocess.CalledProcessError) as exc:
        raise AgentSpecVersionError(
            "Could not verify the AgentSpec checkout at "
            + str(repository)
            + "."
        ) from exc

    commit = completed.stdout.strip()

    if commit != AGENTSPEC_PINNED_COMMIT:
        raise AgentSpecVersionError(
            "AgentSpec checkout is at "
            + repr(commit)
            + ", expected pinned commit "
            + repr(AGENTSPEC_PINNED_COMMIT)
            + "."
        )

    return commit


def _load_generated_parser(source: Path) -> tuple[Any, Any]:
    """Import the generated AgentSpec lexer and parser from external source."""
    source_text = str(source)

    if source_text not in sys.path:
        sys.path.insert(0, source_text)

    try:
        from spec_lang.AgentSpecLexer import AgentSpecLexer
        from spec_lang.AgentSpecParser import AgentSpecParser
    except Exception as exc:
        raise AgentSpecUnavailableError(
            "AgentSpec parser modules could not be imported from "
            + source_text
            + "."
        ) from exc

    return AgentSpecLexer, AgentSpecParser


def parse_policy_text(
    text: str,
    *,
    agentspec_src: str | Path | None = None,
    verify_commit: bool = True,
) -> list[ParsedRule]:
    """Parse AgentSpec-Commerce policy text with the official generated parser."""
    from antlr4 import CommonTokenStream, InputStream
    from antlr4.error.ErrorListener import ErrorListener

    source = resolve_agentspec_src(agentspec_src)

    if verify_commit:
        verify_pinned_checkout(source)

    AgentSpecLexer, AgentSpecParser = _load_generated_parser(source)

    class RaisingErrorListener(ErrorListener):
        def syntaxError(
            self,
            recognizer: Any,
            offending_symbol: Any,
            line: int,
            column: int,
            message: str,
            error: Any,
        ) -> None:
            raise AgentSpecSyntaxError(
                f"AgentSpec syntax error at line {line}, "
                f"column {column}: {message}"
            )

    lexer = AgentSpecLexer(InputStream(text))
    lexer.removeErrorListeners()
    lexer.addErrorListener(RaisingErrorListener())

    tokens = CommonTokenStream(lexer)
    parser = AgentSpecParser(tokens)
    parser.removeErrorListeners()
    parser.addErrorListener(RaisingErrorListener())

    tree = parser.program()
    parsed: list[ParsedRule] = []

    for rule_context in tree.rule_():
        rule_id = (
            rule_context.ruleClause()
            .IDENTIFIER()
            .getText()
        )
        event = (
            rule_context.triggerClause()
            .event()
            .getText()
        )

        predicates = list(
            rule_context.checkClause().predicate()
        )
        enforcements = list(
            rule_context.enforceClause().enforcement()
        )

        if len(predicates) != 1:
            raise AgentSpecPolicyShapeError(
                f"Rule {rule_id!r} must contain exactly one predicate."
            )

        if len(enforcements) != 1:
            raise AgentSpecPolicyShapeError(
                f"Rule {rule_id!r} must contain exactly one enforcement."
            )

        predicate_function = predicates[0].predicate_func()

        if predicate_function is None:
            raise AgentSpecPolicyShapeError(
                f"Rule {rule_id!r} must use a versioned commerce "
                "predicate such as privacy_violation(1)."
            )

        predicate_name = (
            predicate_function.IDENTIFIER().getText()
        )
        predicate_version_text = (
            predicate_function.number().getText()
        )

        try:
            predicate_version = int(predicate_version_text)
        except ValueError as exc:
            raise AgentSpecPolicyShapeError(
                f"Rule {rule_id!r} has a non-integer predicate version: "
                f"{predicate_version_text!r}."
            ) from exc

        enforcement_token = enforcements[0].ENFORCEMENT()

        if enforcement_token is None:
            raise AgentSpecPolicyShapeError(
                f"Rule {rule_id!r} must use a named AgentSpec enforcement."
            )

        start = rule_context.start.start
        stop = rule_context.stop.stop
        raw = text[start : stop + 1]

        parsed.append(
            ParsedRule(
                rule_id=rule_id,
                event=event,
                predicate_name=predicate_name,
                predicate_version=predicate_version,
                enforcement=enforcement_token.getText(),
                raw=raw,
            )
        )

    if not parsed:
        raise AgentSpecPolicyShapeError(
            "AgentSpec-Commerce policy contains no rules."
        )

    return parsed


def load_policy(
    path: str | Path = DEFAULT_POLICY_PATH,
    *,
    agentspec_src: str | Path | None = None,
    verify_commit: bool = True,
) -> list[ParsedRule]:
    """Load and parse an AgentSpec-Commerce policy file."""
    policy_path = Path(path)

    if not policy_path.is_file():
        raise AgentSpecPolicyError(
            "AgentSpec-Commerce policy file not found: "
            + str(policy_path)
        )

    return parse_policy_text(
        policy_path.read_text(encoding="utf-8"),
        agentspec_src=agentspec_src,
        verify_commit=verify_commit,
    )
