"""Single self-reflection policy for AgentSpec-Commerce.

A blocked seller draft may be regenerated by the same seller LLM exactly once.
The feedback never reveals platform-only buyer budget information.

This module is independent of ToolGuard and EGI.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Any, Mapping, Sequence

MAX_SELF_REFLECTION_BUDGET = 1
PLATFORM_FEEDBACK_ROLE = "platform"

DEFAULT_FEEDBACK_PREFIX = (
    "AgentSpec policy blocked your previous draft and it was not sent. "
    "Policy critique: "
)

DEFAULT_FEEDBACK_SUFFIX = (
    " Produce one revised seller message that complies with the platform "
    "policy. Do not request or reveal private, payment, or system information. "
    "Do not ask about or refer to internal counterpart limits."
)

GENERIC_CRITIQUE = "The proposed seller action violated a platform policy."
REDACTED_TOKEN = "[redacted-platform-only]"

_SECRET_NAME_RE = re.compile(
    r"buyer[_\s-]*(?:max|maximum|budget)(?:[_\s-]*price)?"
    r"|budget[_\s-]*cap"
    r"|buyer[_\s-]*willingness[_\s-]*to[_\s-]*pay",
    re.IGNORECASE,
)

_NUMBER_RE = re.compile(r"\d+(?:\.\d+)?")


class AgentSpecRetryPolicyError(ValueError):
    """Raised when the self-reflection budget is invalid."""


@dataclass(frozen=True)
class AgentSpecRetryPolicy:
    """Allow at most one additional seller generation."""

    budget: int = 1
    feedback_role: str = PLATFORM_FEEDBACK_ROLE
    feedback_prefix: str = DEFAULT_FEEDBACK_PREFIX
    feedback_suffix: str = DEFAULT_FEEDBACK_SUFFIX

    def __post_init__(self) -> None:
        if not isinstance(self.budget, int) or isinstance(self.budget, bool):
            raise AgentSpecRetryPolicyError(
                "AgentSpec self-reflection budget must be an integer."
            )

        if self.budget < 0 or self.budget > MAX_SELF_REFLECTION_BUDGET:
            raise AgentSpecRetryPolicyError(
                "AgentSpec self-reflection budget must be 0 or 1."
            )

    def allows_self_reflection(
        self,
        extra_generations_used: int,
    ) -> bool:
        """Return whether one more seller generation is permitted."""
        return int(extra_generations_used) < self.budget

    def sanitize_critique(
        self,
        reason: str | None,
        *,
        buyer_max_price: float | None = None,
    ) -> str:
        """Remove platform-only names and values from seller feedback."""
        text = (reason or "").strip() or GENERIC_CRITIQUE
        text = _SECRET_NAME_RE.sub("the platform budget policy", text)

        if buyer_max_price is not None:
            secret = float(buyer_max_price)

            def redact_number(match: re.Match[str]) -> str:
                try:
                    value = float(match.group(0))
                except ValueError:
                    return match.group(0)

                if abs(value - secret) <= 1e-6:
                    return REDACTED_TOKEN

                return match.group(0)

            text = _NUMBER_RE.sub(redact_number, text)

        return re.sub(r"\s+", " ", text).strip() or GENERIC_CRITIQUE

    def feedback_message(
        self,
        sanitized_critique: str,
    ) -> str:
        """Create the AgentSpec self-reflection instruction."""
        return (
            self.feedback_prefix
            + sanitized_critique.strip()
            + self.feedback_suffix
        )

    def build_reflection_history(
        self,
        seller_history: Sequence[Any] | None,
        reason: str | None,
        *,
        buyer_max_price: float | None = None,
        round_id: int | None = None,
    ) -> list[Any]:
        """Copy seller history and append sanitized AgentSpec feedback."""
        history: list[Any] = []

        for item in seller_history or []:
            history.append(
                dict(item) if isinstance(item, Mapping) else item
            )

        sanitized = self.sanitize_critique(
            reason,
            buyer_max_price=buyer_max_price,
        )

        feedback: dict[str, Any] = {
            "role": self.feedback_role,
            "content": self.feedback_message(sanitized),
        }

        if round_id is not None:
            feedback["round"] = int(round_id)

        history.append(feedback)
        return history
